image: ubuntu

init:
  - appveyor version
  - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

nuget:
  account_feed: true

test_script:
  - dotnet nuget add source https://ci.appveyor.com/nuget/appveyor-tests --name AccountFeed1 --username USER1 --password psw123 --store-password-in-clear-text
  - cat ~/.nuget/NuGet/NuGet.Config
  - cat ~/.config/NuGet/NuGet.Config
  #- cp ~/.nuget/NuGet/NuGet.Config ~/.config/NuGet
  #- ls ~/.nuget
  - dotnet nuget list source
  - sh: dotnet tool list -g
  - sh: |
        if [[ $(dotnet tool list -g) != *"cake.tool"* ]]; then
          dotnet tool install -g Cake.Tool
        fi
  - ls -ltra ~/.dotnet/tools/
  - sh: |
      mkdir -p ~/.nuget/NuGet
      echo '<?xml version="1.0" encoding="utf-8"?>
      <configuration>
      <packageSources>
      <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
      </packageSources>
      </configuration>' > ~/.nuget/NuGet/NuGet.Config
  - sh: dotnet tool list -g
  - sh: |
        if [[ $(dotnet tool list -g) != *"cake.tool"* ]]; then
          dotnet tool install -g Cake.Tool
        fi
  - ls -ltra ~/.dotnet/tools/
  
build: off
